# Generated by Django 5.2.7 on 2025-10-24 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouses',
            fields=[
                ('wr_number', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('shipper', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PiecesWarehouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('wr_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.warehouses')),
            ],
        ),
    ]
