# Generated by Django 5.2.7 on 2025-10-24 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouses',
            name='cliente',
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('wr_number', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('shipper', models.CharField(max_length=100)),
                ('carrier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceWarehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of', models.CharField(choices=[('PALLETS', 'Pallets'), ('CAJAS', 'Cajas'), ('TAMBORES', 'Tambores'), ('ATADOS', 'Atados'), ('OTRO', 'Otro')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='core.warehouse')),
            ],
        ),
        migrations.DeleteModel(
            name='PiecesWarehouses',
        ),
        migrations.DeleteModel(
            name='Warehouses',
        ),
    ]
