# Generated by Django 5.2.7 on 2025-10-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_warehouses_cliente_warehouse_piecewarehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='container_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='warehouse_files/'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='weight_kgs',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='weight_lbs',
            field=models.FloatField(null=True),
        ),
    ]
