# Generated by Django 5.2.7 on 2025-10-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_warehouse_container_number_warehouse_uploaded_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='weight_kgs',
            field=models.FloatField(),
        ),
    ]
