# Generated by Django 5.2.7 on 2025-10-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_warehouse_weight_kgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo')], max_length=20, null=True),
        ),
    ]
