# Generated by Django 5.2.7 on 2025-10-27 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_warehouse_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('MARITIMO', 'Marítimo'), ('AEREO', 'Aéreo'), ('TERRESTRE', 'Terrestre')], max_length=20)),
                ('invoice', models.FileField(upload_to='invoices/')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Aprobado / Despachando'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill_of_lading', models.FileField(blank=True, null=True, upload_to='bol/')),
                ('bol_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DispatchRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.dispatchrequest')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_items', to='core.warehouse')),
            ],
            options={
                'unique_together': {('dispatch', 'warehouse')},
            },
        ),
    ]
