# Generated by Django 5.2.7 on 2025-10-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_dispatchrequest_dispatchrequestitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchrequest',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de revisión'), ('APROBADO', 'Aprobado / En proceso'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LISTO', 'Listo')], default='PENDIENTE', max_length=20),
        ),
    ]
