# Generated by Django 5.2.7 on 2025-10-28 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_dispatchrequest_status_alter_warehouse_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PieceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=1)),
                ('weight_lbs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('weight_kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.piecewarehouse')),
            ],
            options={
                'ordering': ('piece', 'index'),
                'unique_together': {('piece', 'index')},
            },
        ),
    ]
