# Generated by Django 5.2.7 on 2025-10-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_warehousedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='foots',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='invoice_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='po',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='tracking',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
