# Generated by Django 5.2.7 on 2025-10-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_warehouse_invoice_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='invoice_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='tracking',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
